server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/user/**
        - id: business
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/article/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600
  data:
    redis:
      host: 127.0.0.1
      port: 6379
