server:
  port: 8081
  tomcat:
    accept-count: 10000
    threads:
      max: 500
      min-spare: 50
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ahut_forum?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 86530890a
    hikari:
      maximum-pool-size: 1000
      minimum-idle: 100
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: llgElUzxhvJ4m05CaKSY


  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 20
          # 连接池中的最小空闲连接
          min-idle: 0

sa-token:
  jwt-secret-key: asdhkasdbascbasbchajsbchjabshcbashdjajs
logging:
  level:
    sql: trace
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

