WEBSOCKET ws://localhost:8082/chat/123
Content-Type: application/json // used only for IDE highlighting.
// Highlighting is applied for each message independently.


{
    "message": "客户端1，已连接"
}
###
WEBSOCKET ws://localhost:8082/chat/456
Content-Type: application/json // used only for IDE highlighting.
// Highlighting is applied for each message independently.

{
  "message": "客户端2，已连接"
}
###
