POST http://localhost:8081/article/saveArticle
Content-Type: application/json

{
  "content": "安徽工业大学",
  "likeCount": 0,
  "commentCount": 0
}
###
GET http://localhost:8081/article/getArticles?page=1&size=10
