POST http://localhost:8081/article/saveArticle
Content-Type: application/json

{
  "title": "奇迹真的有望发生，“旅行者 1 号”传回完整转储信号：有助于恢复联系  ",
  "content": "IT之家 3 月 16 日消息，美国宇航局（NASA）近日发布新闻稿，表示成功连接“旅行者 1 号”的机载飞行数据系统（FSD）存储器，认为后续有概率恢复和该航天器的联系。“旅行者 1 号”上共有 3 台机载计算机，而其中的 FSD 存储器主要负责打包科学数据和遥测数据，然后将其发送到地球。“旅行者 1 号”自 2023 年 11 月以来，一直在向地球传输一组毫无意义的 1 和 0，而不是星载遥测和科学数据。IT之家注：“旅行者 1 号”是目前距离地球最远的航天器，距离地球约 240 亿公里，目前，旅行者一号继续以每小时 3.8 万英里（6.11 万公里）的速度飞向未知世界。美国宇航局旗下喷气动力试验室（JPL）今年 2 月表示，想要让“旅行者 1 号”恢复和地面的通信，只能等待“奇迹”的发生。美国宇航局在新闻稿中认为，可能是由于 FDS 的 RAM 出现故障导致的。美国宇航局向“旅行者 1 号”发送了特别的指令，强制要求“旅行者 1 号”执行各种计算机序列，希望能探测到 FDS 存储器内受损的扇区。美国宇航局于 3 月 3 日收到了探测器的回复，虽然大部分数据依然难以辨认，不过也发现了一些特别的数据。美国宇航局 3 月 7 日开始解码这些信息，经过 3 天的不懈努力，发现该信号包含完整的 FSD 内存转储，通过了解这些数据可以确定根源和找到潜在解决方案。美国国家航空航天局（NASA）澄清说，该小组将继续分析所获得的数据，现阶段不会盲目实施各种修复方案。",
  "likeCount": 0,
  "commentCount": 0
}
###
GET http://localhost:8081/article/getArticles?page=1&size=10
