name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
#    strategy:
#      matrix:
#        module: [ article_mod ] # 动态生成或手动列出所有模块
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 添加 Maven 构建步骤
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        working-directory: .
        run: mvn clean package -DskipTests

      # 前端构建步骤
      - name: Build Frontend
        working-directory: UserWeb/forum
        run: |
          npm install -g @vue/cli # 全局安装Vue CLI
          npm install --legacy-peer-deps
          vue-cli-service build --mode production

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          password: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      # 后端镜像构建与推送
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.ALIYUN_REGISTRY}}/lituizi/ahut_forum_backend:latest

      # 前端镜像构建与推送
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: UserWeb/forum
          file: UserWeb/forum/Dockerfile
          push: true
          tags: ${{secrets.ALIYUN_REGISTRY}}/lituizi/ahut_forum_frontend:latest
